<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Доска </title>
    <style>

    </style>
</head>

<body>
    <canvas id="hexCanvas" width="1000" height="1000"></canvas>
    <pre id="output"></pre>
    <script src="/js/board.js"></script>
<!--    <script src="/js/alert.js"></script>-->
</body>

</html>

